"""Reconcile MemoryGuard-owned Codex hook enablement and trust.

Codex persists hook trust separately from ``hooks.json``.  Reinstalling or
rewriting the generated hook file can therefore leave correct MemoryGuard
handlers present but disabled or marked modified.  This module uses Codex's
public app-server protocol instead of editing ``config.toml`` text directly:

* ``hooks/list`` discovers the exact effective handlers and current hashes;
* only user-level command hooks generated by MemoryGuard are eligible;
* ``config/read`` supplies the optimistic-concurrency version of user config;
* ``config/batchWrite`` updates only ``enabled`` and ``trusted_hash`` leaves;
* a second ``hooks/list`` proves the resulting runtime view.

Unrelated hooks, plugin hooks, project-local hooks, and malformed duplicates are
never trusted or toggled.  Failures are returned as small JSON-safe diagnostics
so provider installation can remain recoverable without pretending success.
"""

from __future__ import annotations

import argparse
import json
import os
import queue
import re
import subprocess
import threading
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Protocol


HOOK_MODULE_MARKER = "memoryguard.host_hooks"
MANAGED_BY_MARKER = "--managed-by memoryguard"
EXPECTED_EVENTS: dict[str, str] = {
    "sessionStart": "session_start",
    "subagentStart": "subagent_start",
    "userPromptSubmit": "user_prompt",
    "preToolUse": "pre_tool",
    "postToolUse": "post_tool",
    "preCompact": "pre_compact",
    "stop": "stop",
}
DEFAULT_TIMEOUT_SECONDS = 30.0
_MAX_STDERR_CHARS = 8_000
_OPTION_RE_TEMPLATE = r"(?:^|\s){option}(?:=|\s+)(?:\"([^\"]+)\"|'([^']+)'|([^\s]+))"


class CodexHookTrustError(RuntimeError):
    """Expected app-server, discovery, or configuration reconciliation failure."""

    def __init__(self, reason: str, detail: str = "") -> None:
        super().__init__(reason)
        self.reason = reason
        self.detail = detail


@dataclass(frozen=True, slots=True)
class ManagedHook:
    key: str
    event_name: str
    command: str
    current_hash: str
    enabled: bool
    trust_status: str
    source_path: str


@dataclass(frozen=True, slots=True)
class HookTrustResult:
    status: str
    reason: str
    enabled: bool
    verified: bool
    managed_count: int
    expected_count: int
    changed_count: int
    trusted_count: int
    events: tuple[str, ...]
    config_version_before: str = ""
    config_version_after: str = ""
    detail: str = ""
    warnings: tuple[str, ...] = ()
    errors: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["events"] = list(self.events)
        data["warnings"] = list(self.warnings)
        data["errors"] = list(self.errors)
        return data


class AppServerClient(Protocol):
    def request(self, method: str, params: Any) -> dict[str, Any]: ...

    def close(self) -> None: ...


class _JsonLineAppServerClient:
    """Small synchronous JSONL client for ``codex app-server --stdio``."""

    def __init__(self, codex_cli: str, *, timeout_seconds: float) -> None:
        self.timeout_seconds = max(1.0, float(timeout_seconds))
        creationflags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
        environment = os.environ.copy()
        environment["CODEX_HOME"] = str(_codex_home())
        self._process = subprocess.Popen(
            [codex_cli, "app-server", "--stdio"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
            creationflags=creationflags,
            env=environment,
        )
        if self._process.stdin is None or self._process.stdout is None:
            self.close()
            raise CodexHookTrustError("app_server_stdio_unavailable")
        self._messages: queue.Queue[str | None] = queue.Queue()
        self._stderr: list[str] = []
        self._stderr_chars = 0
        self._next_id = 1
        self._stdout_thread = threading.Thread(
            target=self._read_stdout,
            name="memoryguard-codex-app-server-stdout",
            daemon=True,
        )
        self._stderr_thread = threading.Thread(
            target=self._read_stderr,
            name="memoryguard-codex-app-server-stderr",
            daemon=True,
        )
        self._stdout_thread.start()
        self._stderr_thread.start()
        self._initialize()

    def _read_stdout(self) -> None:
        stdout = self._process.stdout
        if stdout is None:
            self._messages.put(None)
            return
        try:
            for line in iter(stdout.readline, ""):
                self._messages.put(line)
        finally:
            self._messages.put(None)

    def _read_stderr(self) -> None:
        stderr = self._process.stderr
        if stderr is None:
            return
        for line in iter(stderr.readline, ""):
            if self._stderr_chars >= _MAX_STDERR_CHARS:
                continue
            remaining = _MAX_STDERR_CHARS - self._stderr_chars
            fragment = line[:remaining]
            self._stderr.append(fragment)
            self._stderr_chars += len(fragment)

    def _stderr_text(self) -> str:
        return "".join(self._stderr).strip()

    def _initialize(self) -> None:
        response = self.request(
            "initialize",
            {
                "clientInfo": {
                    "name": "memoryguard-hook-reconcile",
                    "title": "MemoryGuard Hook Reconcile",
                    "version": "1.0.0",
                },
                "capabilities": {},
            },
        )
        result = response.get("result")
        if not isinstance(result, dict) or not str(result.get("codexHome") or ""):
            raise CodexHookTrustError(
                "app_server_initialize_invalid",
                self._stderr_text(),
            )

    def request(self, method: str, params: Any) -> dict[str, Any]:
        process = self._process
        stdin = process.stdin
        if stdin is None or process.poll() is not None:
            raise CodexHookTrustError(
                "app_server_not_running",
                self._stderr_text(),
            )
        request_id = self._next_id
        self._next_id += 1
        payload = {
            "id": request_id,
            "method": method,
            "params": params,
        }
        try:
            stdin.write(json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n")
            stdin.flush()
        except (BrokenPipeError, OSError) as exc:
            raise CodexHookTrustError(
                "app_server_write_failed",
                type(exc).__name__,
            ) from exc

        deadline = time.monotonic() + self.timeout_seconds
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise CodexHookTrustError(
                    "app_server_request_timeout",
                    method,
                )
            try:
                line = self._messages.get(timeout=remaining)
            except queue.Empty as exc:
                raise CodexHookTrustError(
                    "app_server_request_timeout",
                    method,
                ) from exc
            if line is None:
                raise CodexHookTrustError(
                    "app_server_connection_closed",
                    self._stderr_text(),
                )
            try:
                message = json.loads(line)
            except (TypeError, ValueError):
                continue
            if not isinstance(message, dict) or message.get("id") != request_id:
                # Notifications and unrelated responses are connection-local
                # diagnostics; this client has only one in-flight request.
                continue
            error = message.get("error")
            if isinstance(error, dict):
                reason = str(error.get("message") or "app_server_error")
                code = str(error.get("code") or "")
                data = error.get("data")
                detail = json.dumps(
                    {"code": code, "data": data},
                    ensure_ascii=False,
                    sort_keys=True,
                )
                raise CodexHookTrustError(reason, detail)
            return message

    def close(self) -> None:
        process = getattr(self, "_process", None)
        if process is None:
            return
        try:
            if process.stdin is not None and not process.stdin.closed:
                process.stdin.close()
        except OSError:
            pass
        if process.poll() is None:
            try:
                process.terminate()
                process.wait(timeout=3)
            except (OSError, subprocess.TimeoutExpired):
                try:
                    process.kill()
                except OSError:
                    pass
        for stream in (process.stdout, process.stderr):
            try:
                if stream is not None:
                    stream.close()
            except OSError:
                pass

    def __enter__(self) -> "_JsonLineAppServerClient":
        return self

    def __exit__(self, *_exc: object) -> None:
        self.close()


def _codex_home() -> Path:
    configured = str(os.environ.get("CODEX_HOME", "") or "").strip()
    return (
        Path(configured).expanduser().resolve(strict=False)
        if configured
        else (Path.home() / ".codex").resolve(strict=False)
    )


def _find_codex_cli(explicit: str | os.PathLike[str] | None = None) -> str:
    if explicit:
        candidate = Path(explicit).expanduser().resolve(strict=False)
        if candidate.is_file():
            return str(candidate)
        raise CodexHookTrustError("codex_cli_not_found", str(candidate))
    try:
        from .host_agent_backend import _find_codex_cli

        resolved = _find_codex_cli()
    except Exception as exc:  # pragma: no cover - defensive import seam
        raise CodexHookTrustError(
            "codex_cli_discovery_failed",
            type(exc).__name__,
        ) from exc
    if not resolved:
        raise CodexHookTrustError("codex_cli_not_found")
    return str(resolved)


def _command_option(command: str, option: str) -> str:
    pattern = _OPTION_RE_TEMPLATE.format(option=re.escape(option))
    match = re.search(pattern, str(command or ""))
    if match is None:
        return ""
    return next((str(value) for value in match.groups() if value), "")


def _same_path(left: str | os.PathLike[str], right: Path) -> bool:
    try:
        return os.path.normcase(
            os.path.abspath(os.fspath(Path(left).expanduser()))
        ) == os.path.normcase(os.path.abspath(os.fspath(right)))
    except (OSError, TypeError, ValueError):
        return False


def _iter_generated_handlers(data: Mapping[str, Any]) -> Iterable[Mapping[str, Any]]:
    hooks = data.get("hooks")
    if not isinstance(hooks, dict):
        return
    for groups in hooks.values():
        if not isinstance(groups, list):
            continue
        for group in groups:
            if not isinstance(group, dict):
                continue
            handlers = group.get("hooks")
            if not isinstance(handlers, list):
                continue
            for handler in handlers:
                if isinstance(handler, dict):
                    yield handler


def _discover_existing_binding(hooks_path: Path) -> tuple[str, str, str]:
    """Return the sole generated workspace/Agent/group binding in hooks.json."""
    try:
        data = json.loads(hooks_path.read_text(encoding="utf-8"))
    except (OSError, TypeError, ValueError) as exc:
        raise CodexHookTrustError(
            "codex_hooks_read_failed",
            type(exc).__name__,
        ) from exc
    bindings: set[tuple[str, str, str]] = set()
    found = 0
    valid_events = set(EXPECTED_EVENTS.values())
    for handler in _iter_generated_handlers(data):
        command = str(
            handler.get("commandWindows")
            or handler.get("command")
            or ""
        )
        if (
            HOOK_MODULE_MARKER not in command
            or MANAGED_BY_MARKER not in command
            or _command_option(command, "--managed-by") != "memoryguard"
            or _command_option(command, "--provider").lower() != "codex"
        ):
            continue
        event = _command_option(command, "--event")
        workspace = _command_option(command, "--workspace")
        agent_id = _command_option(command, "--agent-id")
        group_id = _command_option(command, "--share-group-id")
        if (
            event not in valid_events
            or not workspace
            or not agent_id
            or not group_id
        ):
            raise CodexHookTrustError(
                "generated_hook_binding_invalid",
                event or "missing_event",
            )
        found += 1
        bindings.add((workspace, agent_id, group_id))
    if found == 0:
        raise CodexHookTrustError("managed_hooks_not_found")
    if len(bindings) != 1:
        raise CodexHookTrustError(
            "managed_hook_binding_ambiguous",
            f"binding_count={len(bindings)}",
        )
    return next(iter(bindings))


def _managed_hook_from_metadata(
    raw: Mapping[str, Any],
    *,
    hooks_path: Path,
) -> ManagedHook | None:
    command = str(raw.get("command") or "")
    event_name = str(raw.get("eventName") or "")
    expected_event = EXPECTED_EVENTS.get(event_name)
    if (
        expected_event is None
        or str(raw.get("handlerType") or "") != "command"
        or str(raw.get("source") or "") != "user"
        or not _same_path(str(raw.get("sourcePath") or ""), hooks_path)
        or HOOK_MODULE_MARKER not in command
        or MANAGED_BY_MARKER not in command
        or _command_option(command, "--managed-by") != "memoryguard"
        or _command_option(command, "--provider").lower() != "codex"
        or _command_option(command, "--event") != expected_event
        or not _command_option(command, "--workspace")
        or not _command_option(command, "--agent-id")
        or not _command_option(command, "--share-group-id")
    ):
        return None
    key = str(raw.get("key") or "")
    current_hash = str(raw.get("currentHash") or "")
    if not key or not current_hash.startswith("sha256:"):
        return None
    return ManagedHook(
        key=key,
        event_name=event_name,
        command=command,
        current_hash=current_hash,
        enabled=bool(raw.get("enabled")),
        trust_status=str(raw.get("trustStatus") or ""),
        source_path=str(raw.get("sourcePath") or ""),
    )


def _select_managed_hooks(
    response: Mapping[str, Any],
    *,
    hooks_path: Path,
) -> tuple[tuple[ManagedHook, ...], tuple[str, ...], tuple[str, ...]]:
    result = response.get("result")
    entries = result.get("data") if isinstance(result, dict) else None
    if not isinstance(entries, list):
        raise CodexHookTrustError("hooks_list_invalid")
    hooks: list[ManagedHook] = []
    warnings: list[str] = []
    errors: list[str] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        for warning in entry.get("warnings") or []:
            warnings.append(str(warning))
        for error in entry.get("errors") or []:
            if isinstance(error, dict):
                errors.append(str(error.get("message") or "hook_error"))
            else:
                errors.append(str(error))
        for raw in entry.get("hooks") or []:
            if not isinstance(raw, dict):
                continue
            hook = _managed_hook_from_metadata(raw, hooks_path=hooks_path)
            if hook is not None:
                hooks.append(hook)
    hooks.sort(key=lambda item: (item.event_name, item.key))
    return tuple(hooks), tuple(warnings), tuple(errors)


def _validate_complete_managed_set(hooks: Iterable[ManagedHook]) -> tuple[str, ...]:
    by_event: dict[str, list[ManagedHook]] = {}
    for hook in hooks:
        by_event.setdefault(hook.event_name, []).append(hook)
    missing = sorted(set(EXPECTED_EVENTS) - set(by_event))
    duplicates = sorted(
        event for event, items in by_event.items() if len(items) != 1
    )
    unexpected = sorted(set(by_event) - set(EXPECTED_EVENTS))
    problems: list[str] = []
    if missing:
        problems.append("missing=" + ",".join(missing))
    if duplicates:
        problems.append("duplicates=" + ",".join(duplicates))
    if unexpected:
        problems.append("unexpected=" + ",".join(unexpected))
    return tuple(problems)


def _user_layer_version(response: Mapping[str, Any], config_path: Path) -> str:
    result = response.get("result")
    layers = result.get("layers") if isinstance(result, dict) else None
    if not isinstance(layers, list):
        return ""
    for layer in layers:
        if not isinstance(layer, dict):
            continue
        name = layer.get("name")
        if not isinstance(name, dict) or str(name.get("type") or "") != "user":
            continue
        file_value = str(name.get("file") or "")
        if file_value and not _same_path(file_value, config_path):
            continue
        version = str(layer.get("version") or "")
        if version:
            return version
    return ""


def _effective_hook_state(response: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    result = response.get("result")
    config = result.get("config") if isinstance(result, dict) else None
    hooks = config.get("hooks") if isinstance(config, dict) else None
    state = hooks.get("state") if isinstance(hooks, dict) else None
    if not isinstance(state, dict):
        return {}
    normalized: dict[str, dict[str, Any]] = {}
    for key, value in state.items():
        if isinstance(value, dict):
            normalized[str(key)] = dict(value)
    return normalized


def _key_path(hook_key: str, field: str) -> str:
    # Codex key paths accept TOML-quoted path components.  JSON string syntax
    # is valid TOML basic-string syntax and safely escapes Windows backslashes.
    return "hooks.state." + json.dumps(hook_key, ensure_ascii=False) + "." + field


def _build_edits(
    hooks: Iterable[ManagedHook],
    state: Mapping[str, Mapping[str, Any]],
    *,
    enabled: bool,
) -> list[dict[str, Any]]:
    edits: list[dict[str, Any]] = []
    for hook in hooks:
        current = state.get(hook.key) or {}
        if bool(current.get("enabled")) is not enabled:
            edits.append(
                {
                    "keyPath": _key_path(hook.key, "enabled"),
                    "value": enabled,
                    "mergeStrategy": "upsert",
                }
            )
        if enabled and str(current.get("trusted_hash") or "") != hook.current_hash:
            edits.append(
                {
                    "keyPath": _key_path(hook.key, "trusted_hash"),
                    "value": hook.current_hash,
                    "mergeStrategy": "upsert",
                }
            )
    return edits


def _verify_hooks(
    hooks: Iterable[ManagedHook],
    *,
    enabled: bool,
) -> tuple[bool, int]:
    items = tuple(hooks)
    if len(items) != len(EXPECTED_EVENTS):
        return False, 0
    trusted_count = sum(
        1 for hook in items if hook.trust_status in {"trusted", "managed"}
    )
    if enabled:
        return (
            all(hook.enabled for hook in items)
            and trusted_count == len(items),
            trusted_count,
        )
    return all(not hook.enabled for hook in items), trusted_count


def ensure_existing_codex_memoryguard_hooks(
    *,
    codex_cli: str | os.PathLike[str] | None = None,
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
    manager_factory: Callable[[str | Path], Any] | None = None,
    mode_getter: Callable[[str | Path, str, str], str] | None = None,
) -> dict[str, Any]:
    """Rebuild and trust the sole existing generated Codex binding.

    This is an upgrade/repair seam, not a generic installer.  It refuses to
    guess when ``hooks.json`` contains no MemoryGuard binding or more than one
    distinct workspace/Agent/group binding.
    """
    hooks_path = _codex_home() / "hooks.json"
    try:
        if not hooks_path.is_file():
            raise CodexHookTrustError("codex_hooks_file_missing", str(hooks_path))
        workspace, agent_id, group_id = _discover_existing_binding(hooks_path)
        if manager_factory is None or mode_getter is None:
            from .host_hooks import HostHookManager, get_hook_mode

            active_manager_factory = manager_factory or HostHookManager
            active_mode_getter = mode_getter or get_hook_mode
        else:
            active_manager_factory = manager_factory
            active_mode_getter = mode_getter
        mode = str(active_mode_getter(workspace, "codex", agent_id) or "enforce")
        result = active_manager_factory(workspace).install(
            "codex",
            agent_instance_id=agent_id,
            share_group_id=group_id,
            mode=mode,
            reconcile_trust=False,
        )
        if not result.get("configured"):
            return {
                "status": "degraded",
                "reason": "managed_hook_reinstall_failed",
                "verified": False,
                "install": result,
            }
        trust = reconcile_codex_memoryguard_hooks(
            cwd=workspace,
            enabled=True,
            codex_cli=codex_cli,
            timeout_seconds=timeout_seconds,
        )
        return {
            "status": "ok" if trust.get("verified") else "degraded",
            "reason": "ensured" if trust.get("verified") else "trust_reconcile_failed",
            "verified": bool(trust.get("verified")),
            "workspace": workspace,
            "agent_instance_id": agent_id,
            "share_group_id": group_id,
            "install": result,
            "hook_trust": trust,
        }
    except CodexHookTrustError as exc:
        return {
            "status": "degraded",
            "reason": exc.reason,
            "verified": False,
            "detail": exc.detail,
        }
    except Exception as exc:  # pragma: no cover - final fail-open boundary
        return {
            "status": "degraded",
            "reason": "unexpected_ensure_failure",
            "verified": False,
            "detail": type(exc).__name__,
        }


def inspect_codex_memoryguard_hooks(
    *,
    cwd: str | Path,
    codex_cli: str | os.PathLike[str] | None = None,
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
    client_factory: Callable[[str, float], AppServerClient] | None = None,
) -> dict[str, Any]:
    """Read the effective Codex runtime view without changing user config."""
    expected_count = len(EXPECTED_EVENTS)
    client: AppServerClient | None = None
    try:
        executable = _find_codex_cli(codex_cli)
        hooks_path = _codex_home() / "hooks.json"
        if not hooks_path.is_file():
            raise CodexHookTrustError("codex_hooks_file_missing", str(hooks_path))
        factory = client_factory or (
            lambda cli, timeout: _JsonLineAppServerClient(
                cli,
                timeout_seconds=timeout,
            )
        )
        client = factory(executable, float(timeout_seconds))
        listed = client.request("hooks/list", {"cwds": [str(Path(cwd))]})
        managed, warnings, errors = _select_managed_hooks(
            listed,
            hooks_path=hooks_path,
        )
        problems = _validate_complete_managed_set(managed)
        verified, trusted_count = _verify_hooks(managed, enabled=True)
        disabled_events = sorted(
            hook.event_name for hook in managed if not hook.enabled
        )
        untrusted_events = sorted(
            hook.event_name
            for hook in managed
            if hook.trust_status not in {"trusted", "managed"}
        )
        detail_parts = list(problems)
        if disabled_events:
            detail_parts.append("disabled=" + ",".join(disabled_events))
        if untrusted_events:
            detail_parts.append("untrusted=" + ",".join(untrusted_events))
        return HookTrustResult(
            status="ok" if verified else "degraded",
            reason="trusted_and_enabled" if verified else "hook_runtime_state_invalid",
            enabled=True,
            verified=verified,
            managed_count=len(managed),
            expected_count=expected_count,
            changed_count=0,
            trusted_count=trusted_count,
            events=tuple(hook.event_name for hook in managed),
            detail=";".join(detail_parts),
            warnings=warnings,
            errors=errors,
        ).to_dict()
    except CodexHookTrustError as exc:
        return HookTrustResult(
            status="degraded",
            reason=exc.reason,
            enabled=True,
            verified=False,
            managed_count=0,
            expected_count=expected_count,
            changed_count=0,
            trusted_count=0,
            events=(),
            detail=exc.detail,
        ).to_dict()
    except Exception as exc:  # pragma: no cover - final fail-open boundary
        return HookTrustResult(
            status="degraded",
            reason="unexpected_inspection_failure",
            enabled=True,
            verified=False,
            managed_count=0,
            expected_count=expected_count,
            changed_count=0,
            trusted_count=0,
            events=(),
            detail=type(exc).__name__,
        ).to_dict()
    finally:
        if client is not None:
            try:
                client.close()
            except Exception:
                pass


def reconcile_codex_memoryguard_hooks(
    *,
    cwd: str | Path,
    enabled: bool = True,
    codex_cli: str | os.PathLike[str] | None = None,
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
    client_factory: Callable[[str, float], AppServerClient] | None = None,
) -> dict[str, Any]:
    """Enable/trust or disable only the exact generated MemoryGuard Codex hooks."""
    expected_count = len(EXPECTED_EVENTS)
    warnings: tuple[str, ...] = ()
    errors: tuple[str, ...] = ()
    client: AppServerClient | None = None
    try:
        executable = _find_codex_cli(codex_cli)
        hooks_path = _codex_home() / "hooks.json"
        config_path = _codex_home() / "config.toml"
        if not hooks_path.is_file():
            raise CodexHookTrustError("codex_hooks_file_missing", str(hooks_path))
        if not config_path.is_file():
            raise CodexHookTrustError("codex_config_file_missing", str(config_path))

        factory = client_factory or (
            lambda cli, timeout: _JsonLineAppServerClient(
                cli,
                timeout_seconds=timeout,
            )
        )
        client = factory(executable, float(timeout_seconds))
        listed = client.request("hooks/list", {"cwds": [str(Path(cwd))]})
        managed, warnings, errors = _select_managed_hooks(
            listed,
            hooks_path=hooks_path,
        )
        problems = _validate_complete_managed_set(managed)
        if problems:
            return HookTrustResult(
                status="degraded",
                reason="managed_hook_set_incomplete",
                enabled=enabled,
                verified=False,
                managed_count=len(managed),
                expected_count=expected_count,
                changed_count=0,
                trusted_count=sum(
                    1
                    for hook in managed
                    if hook.trust_status in {"trusted", "managed"}
                ),
                events=tuple(hook.event_name for hook in managed),
                detail=";".join(problems),
                warnings=warnings,
                errors=errors,
            ).to_dict()

        config_response = client.request(
            "config/read",
            {"cwd": str(Path(cwd)), "includeLayers": True},
        )
        version_before = _user_layer_version(config_response, config_path)
        if not version_before:
            raise CodexHookTrustError("user_config_version_missing")
        state = _effective_hook_state(config_response)
        edits = _build_edits(managed, state, enabled=enabled)
        version_after = version_before
        if edits:
            write_response = client.request(
                "config/batchWrite",
                {
                    "edits": edits,
                    "expectedVersion": version_before,
                    "filePath": str(config_path),
                    "reloadUserConfig": True,
                },
            )
            write_result = write_response.get("result")
            if not isinstance(write_result, dict) or str(write_result.get("status") or "") != "ok":
                raise CodexHookTrustError("config_batch_write_invalid")
            version_after = str(write_result.get("version") or "") or version_before

        verified_response = client.request("hooks/list", {"cwds": [str(Path(cwd))]})
        verified_hooks, verify_warnings, verify_errors = _select_managed_hooks(
            verified_response,
            hooks_path=hooks_path,
        )
        warnings = tuple(dict.fromkeys((*warnings, *verify_warnings)))
        errors = tuple(dict.fromkeys((*errors, *verify_errors)))
        verified, trusted_count = _verify_hooks(
            verified_hooks,
            enabled=enabled,
        )
        return HookTrustResult(
            status="ok" if verified else "degraded",
            reason="reconciled" if edits else "already_current",
            enabled=enabled,
            verified=verified,
            managed_count=len(verified_hooks),
            expected_count=expected_count,
            changed_count=len(edits),
            trusted_count=trusted_count,
            events=tuple(hook.event_name for hook in verified_hooks),
            config_version_before=version_before,
            config_version_after=version_after,
            warnings=warnings,
            errors=errors,
        ).to_dict()
    except CodexHookTrustError as exc:
        return HookTrustResult(
            status="degraded",
            reason=exc.reason,
            enabled=enabled,
            verified=False,
            managed_count=0,
            expected_count=expected_count,
            changed_count=0,
            trusted_count=0,
            events=(),
            detail=exc.detail,
            warnings=warnings,
            errors=errors,
        ).to_dict()
    except Exception as exc:  # pragma: no cover - final fail-open boundary
        return HookTrustResult(
            status="degraded",
            reason="unexpected_reconcile_failure",
            enabled=enabled,
            verified=False,
            managed_count=0,
            expected_count=expected_count,
            changed_count=0,
            trusted_count=0,
            events=(),
            detail=type(exc).__name__,
            warnings=warnings,
            errors=errors,
        ).to_dict()
    finally:
        if client is not None:
            try:
                client.close()
            except Exception:
                pass


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m memoryguard.codex_hook_trust",
        description="Reconcile only MemoryGuard-owned Codex hook trust state.",
    )
    parser.add_argument("state", choices=("on", "off", "ensure"))
    parser.add_argument("--cwd", default=str(Path.cwd()))
    parser.add_argument("--codex-cli", default="")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT_SECONDS)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.state == "ensure":
        result = ensure_existing_codex_memoryguard_hooks(
            codex_cli=args.codex_cli or None,
            timeout_seconds=args.timeout,
        )
    else:
        result = reconcile_codex_memoryguard_hooks(
            cwd=args.cwd,
            enabled=args.state == "on",
            codex_cli=args.codex_cli or None,
            timeout_seconds=args.timeout,
        )
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0 if result.get("verified") else 1


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "CodexHookTrustError",
    "EXPECTED_EVENTS",
    "HOOK_MODULE_MARKER",
    "HookTrustResult",
    "MANAGED_BY_MARKER",
    "ManagedHook",
    "ensure_existing_codex_memoryguard_hooks",
    "inspect_codex_memoryguard_hooks",
    "reconcile_codex_memoryguard_hooks",
]
